import { getPortfolioData } from "@/lib/portfolio-actions"
import { Building, MapPin, ExternalLink, ShieldCheck } from "lucide-react"
import Link from "next/link"
import { notFound } from "next/navigation"

export const metadata = {
    title: 'Developer Portfolio | CodeBoard',
    description: 'A dynamic professional portfolio generated by CodeBoard.'
}

type Params = Promise<{ username: string }>

export default async function PublicPortfolioPage(props: { params: Params }) {
    // 1. Fetch data based on the dynamic URL slug
    const params = await props.params;
    const data = await getPortfolioData(params.username)
    const p = data.profile

    // 2. 404 if no profile exists for this slug or if it's set to private
    if (!p || !p.is_public) {
        notFound()
    }

    // Determine Theme Colors
    const isPurple = p.theme_color === 'purple'
    const isBlue = p.theme_color === 'blue'
    const isGreen = p.theme_color === 'green'
    const themeColorHex = isPurple ? '#a855f7' : isBlue ? '#3b82f6' : isGreen ? '#22c55e' : '#f97316'
    const themeGradient = isPurple ? "from-purple-400 to-blue-400" :
        isBlue ? "from-blue-400 to-cyan-400" :
            isGreen ? "from-green-400 to-emerald-400" :
                "from-orange-400 to-amber-400"

    return (
        <div className="min-h-screen bg-[#0a0a0b] text-white font-sans selection:bg-white/20">
            {/* Top Branding Bar */}
            <div className="w-full border-b border-white/[0.04] bg-[#0c0c0d] py-3 px-6 flex items-center justify-between z-50 sticky top-0 backdrop-blur-md">
                <Link href="/" className="flex items-center gap-2 group">
                    <div className="w-6 h-6 rounded bg-gradient-to-br from-purple-500 to-blue-500 flex items-center justify-center font-black text-[10px] tracking-tighter">
                        CB
                    </div>
                    <span className="font-bold text-sm tracking-tight text-white group-hover:text-purple-400 transition-colors">
                        CodeBoard
                    </span>
                </Link>
                <div className="flex items-center gap-4 text-sm font-medium">
                    <span className="text-gray-500">Powered by CodeBoard</span>
                    <Link href="/sign-up" className={`px-4 py-1.5 rounded-full bg-white/10 hover:bg-white/20 transition-colors text-${p.theme_color}-400`}>
                        Create Yours
                    </Link>
                </div>
            </div>

            <main className="max-w-5xl mx-auto px-6 py-20 pb-32 animate-in fade-in slide-in-from-bottom-8 duration-700">
                {/* Hero Section */}
                <div className="flex flex-col md:flex-row items-center gap-10 relative">
                    {/* Glow effect matching theme */}
                    <div className="absolute top-1/2 left-1/4 -translate-y-1/2 -translate-x-1/2 w-96 h-96 blur-[120px] rounded-full pointer-events-none opacity-20" style={{ backgroundColor: themeColorHex }} />

                    {/* Avatar */}
                    <div className="w-40 h-40 md:w-48 md:h-48 rounded-full bg-gradient-to-br from-[#1a1a1c] to-[#0c0c0c] border border-white/10 flex items-center justify-center shrink-0 overflow-hidden relative shadow-2xl z-10 group">
                        <div className={`absolute inset-0 bg-gradient-to-tr ${themeGradient} opacity-0 group-hover:opacity-20 transition-opacity duration-500`} />
                        <span className={`text-6xl md:text-7xl font-extrabold bg-gradient-to-br ${themeGradient} bg-clip-text text-transparent`}>
                            {p.headline ? p.headline.charAt(0).toUpperCase() : "U"}
                        </span>
                    </div>

                    <div className="flex-1 text-center md:text-left z-10">
                        <h1 className="text-5xl md:text-6xl font-black text-white mb-4 tracking-tight">
                            {params.username.split("-").map(w => w.charAt(0).toUpperCase() + w.slice(1)).join(" ")}
                        </h1>
                        <p className={`text-xl md:text-2xl max-w-2xl font-semibold bg-gradient-to-r ${themeGradient} bg-clip-text text-transparent mb-6 inline-block`}>
                            {p.headline || "Full Stack Developer"}
                        </p>

                        <div className="flex flex-wrap items-center justify-center md:justify-start gap-6 text-gray-400 mb-8 font-medium">
                            {p.location && <span className="flex items-center gap-2"><MapPin className="w-5 h-5 text-gray-500" /> {p.location}</span>}
                            {p.company && <span className="flex items-center gap-2"><Building className="w-5 h-5 text-gray-500" /> {p.company}</span>}
                            <span className="flex items-center gap-2 px-3 py-1 rounded-full bg-white/5 border border-white/10 text-xs">
                                <ShieldCheck className="w-4 h-4 text-green-400" /> Verified CodeBoard Profile
                            </span>
                        </div>

                        {/* Links/CTA Drop-in */}
                        <div className="flex flex-wrap items-center justify-center md:justify-start gap-4">
                            <a
                                href={`mailto:hello@${params.username}.com`}
                                className="px-6 py-3 rounded-full bg-white text-black font-bold hover:scale-105 active:scale-95 transition-transform"
                            >
                                Contact Me
                            </a>
                        </div>
                    </div>
                </div>

                <div className="mt-24 grid grid-cols-1 lg:grid-cols-3 gap-12">
                    {/* Main Content Area */}
                    <div className="lg:col-span-2 space-y-16">
                        {/* About Me */}
                        {p.bio && (
                            <section>
                                <h2 className="text-2xl font-bold text-white mb-6 flex items-center gap-3">
                                    <span style={{ color: themeColorHex }}>//</span> About Me
                                </h2>
                                <div className="prose prose-invert max-w-none prose-p:text-gray-400 prose-p:leading-relaxed prose-p:text-lg">
                                    <p className="whitespace-pre-wrap">{p.bio}</p>
                                </div>
                            </section>
                        )}

                        {/* More Data to come (Experience, Education, Projects) */}
                    </div>

                    {/* Sidebar Area (Skills) */}
                    <div className="space-y-12">
                        {/* Skills data to come */}
                    </div>
                </div>
            </main>
        </div>
    )
}
